Game instruction button
uniba-swt/swtbahn-cli pull request #118
Opened 2023-07-24 06:46 UTC by eyip002

Added tips

2023-09-04 07:25 UTC, BLuedtke requested changes

2023-09-04 07:25 UTC, BLuedtke commented on server/src/assets/game/driver-game.html
> +					<span class='normal'>Possible destinations:</span>
Am Ende mancher Span-Inhalte ist ein Leerzeichen, aber nicht bei allen. Sollte konsistent sein. Betrifft auch andere Spans weiter unten.
At the end of some span-contents there is a space, but not in all cases. This should be made consistent if possible. Also check other spans in this file.

2023-09-04 07:25 UTC, BLuedtke commented on server/src/assets/game/driver-game.html
> +		<div class="m-3"></div>
What is this empty div doing here?

2023-09-04 07:25 UTC, BLuedtke commented on server/src/assets/game/driver-game.html
> +				<span lang="de"><span class="easy">Bitte fahren Sie mit Ihrem Zug zum Zielort und halten Sie dann an</span></span>
I would rephrase the german part a bit:    
"Bitte fahren Sie Ihren Zug zum Ziel und halten Sie kurz vor dem Ziel an"

2023-09-04 07:25 UTC, BLuedtke commented on server/src/assets/game/script-game.js
> +								case "de": $(this).html(`<span class='easy' ${setVisibility(isEasyMode)}>Klicke um den Zug zu fahren</span><span class='normal' ${setVisibility(!isEasyMode)}>Fahre den Zug</span>`);
"Fahre den Zug" -> "Zug fahren", or "Diesen Zug fahren"

2023-09-05 17:54 UTC, eyip002 commented on server/src/assets/game/driver-game.html
> +		<div class="m-3"></div>
To add vertical space

2023-09-08 16:25 UTC, eyip002 commented
@BLuedtke approve?

2023-09-09 13:31 UTC, BLuedtke approved these changes

2023-09-09 13:32 UTC, merged