Merge Mutex and memory fixes
uniba-swt/swtbahn-cli pull request #119
Opened 2023-08-03 16:07 UTC by BLuedtke

This PR addresses 2 areas:
1. Mutex: Up until now, the "grabbed_trains_mutex" is **sometimes** used when reading/writing the grabbed_trains array.  This means there is a lot of potential for bugs due to concurrent/conflicting r/w access. Affected areas are mainly the handler_... files that use the grabbed_trains array directly.
2. Memory: The parsers are currently leaking memory all over the place. I analyzed this with address-sanitizer and adjusted them accordingly. Whilst adjusting the parsers, I also streamlined some of the unnecessarily long ifs into if-elses. Additionally, across most handlers, I added checks for the returns of malloc and strdup. I.e., checking if the memory allocation succeeds. 

Open TODOs that should be discussed/resolved/moved before merging this PR:
- handler_admin line 265: handler_admin doesn't have access to the same constant (TRAIN_DRIVE_TIME_STEP in particular) like handler_driver has, but it is needed here. Maybe move these constants to a header?
-  handler_driver line 894: For releasing a train, the speed is first set to 0. We then wait until the speed actually becomes 0. Only then is the train released. But what if some other thread sets the speed to something != 0 directly after it is set to 0 here? We can't keep the mutex locked, as that prevents progression in the engine container.

Furthermore, whilst some manual testing has been performed, more rigorous use/testing is needed.

I also suggest to squash commits upon merging, as it's, well, quite a lot of experimental small ones.

2023-08-03 16:32 UTC, BLuedtke commented
last_scalar in parser_util was freed a bit too early, causing the parser to act slightly differently in some of the callbacks. Tests now run fine on my machine.

2023-08-04 10:54 UTC, eyip002 requested changes
**Re: handler_driver line 894:** 
- The train is still unavailable while we wait for the train to stop. At this point, only the admin has the ability to set the train's speed.
- The while loop only queries the train speed and does not proactively stop the train if it is still moving. I suggest to remove the loop.

2023-08-04 10:54 UTC, eyip002 commented on server/src/parsers/track_config_parser.c
> +                // transfered here.
transferred

2023-08-04 11:00 UTC, eyip002 commented
Suggested tests:
- [ ] Execute every command available in the Python client: check the returned messages and physical state
- [ ] Try every option available in the web clients (driver, controller, client, game): check the returned messages and physical state
- [ ] Run the physical test cases
- [ ] Check server logs

2023-08-04 12:45 UTC, BLuedtke commented on server/src/handler_driver.c
> +				return false;
oh, yep. Or OCS_INTERNAL_ERROR, but that would not be consistent as we usually just use OCS_NOT_IMPLEMENTED.

2023-08-04 12:47 UTC, BLuedtke commented on server/src/handler_monitor.c
>  			g_string_append_printf(granted_routes, "No granted routes");
Well spotted! That' would have broken quite a few things.

2023-08-04 12:55 UTC, BLuedtke commented on server/src/bahn_data_util.c
>  }
Will remove it. the cached_allocated_str array is still needed for one other use though.

2023-08-04 12:59 UTC, BLuedtke commented on server/src/bahn_data_util.c
> +            syslog_server(LOG_ERR, "get signal state: unable to allocate memory for raw_state");
Good idea. Would only be a problem if `state_query.board_accessory_state.state_id` is null, but this can be checked as well.

2023-08-04 14:17 UTC, eyip002 reviewed
Just needs extensive testing 😄

2023-08-04 16:32 UTC, BLuedtke commented
What does "physical test cases" refer to? There are none for cli, only for bidib. The test script that uses the python client isnt any better than me testing with the python client directly in this case.

2023-08-04 16:44 UTC, BLuedtke commented
Alright, I can't get the reverser state if no train is sitting on the Kehrschleife. But this is the same as on the master branch. If a train is on there, I get the info as intended. So that works, and concludes my testing.

2023-08-04 17:14 UTC, eyip002 commented
Should probably make physical test cases based on `sample_test_script.sh` for switching points and signals, and running a train.

The reverser query behaviour doesn't sound normal. Are you able to get the monitor to print "on" and "off" for the reverser state? 

Is BiDiB Wizard able to read the reverser state?

![2021-08-04-185540_1920x1080_scrot](https://github.com/uniba-swt/swtbahn-cli/assets/7035180/bd917443-4b7f-4360-8386-960ac363a0ca)

2023-08-06 10:12 UTC, BLuedtke commented
I will open a new issue for the reverser problem, as it happens on the master branch too.

2023-08-06 10:13 UTC, BLuedtke commented
The other problem I found is that automatic route driving get's the direction wrong in a very specific situation with the Kehrschleife. Maybe the two problem are interlinked.

2023-09-15 13:27 UTC, eyip002 approved these changes

2023-09-15 13:27 UTC, merged