Add sectional interlocker source file for use in Game on SWTbahn-full
uniba-swt/swtbahn-cli pull request #83
Opened 2022-10-04 08:13 UTC by BLuedtke

Adds the source file for a sectional interlocker in server/src/interlockers called "sectional-swtbahn-full.bahn".

This sectional interlocker is a refactored version of an already tested (on swtbahn-full) interlocker implementing sectional route release. After refactoring, I tested that it still compiles as expected, but have not re-tested it with the model railway. If requested, I can do so before we merge this PR.

It works only for swtbahn-full, as it requires information that is currently not available via the platform config files. It is intended primarily for use in the "game", at least for now - but is not limited to it.

2022-10-04 15:13 UTC, eyip002 commented
Rename to `simple_sectional.bahn`

2022-10-04 16:53 UTC, eyip002 requested changes

2022-10-04 16:53 UTC, eyip002 commented on server/src/interlockers/simple_sectional.bahn
> +def is_occupied_from_preceding_signal_to(string seg_id, string route_id): bool
Would prefer if the loop counters were renamed to some sort of `current_path_index`

2022-10-04 16:53 UTC, eyip002 commented on server/src/interlockers/simple_sectional.bahn
> +        bool path_item_is_signal = is path_item a_signal
Can inline these into the if-condition below. May need to enclose in `( )`

2022-10-04 16:53 UTC, eyip002 commented on server/src/interlockers/simple_sectional.bahn
> +	# 1. Determine the segments where the two routes intersect.
Change tabs into spaces

2022-10-04 16:53 UTC, eyip002 commented on server/src/interlockers/simple_sectional.bahn
> +	if seg_id == "seg1" || seg_id == "seg2" || seg_id == "seg3" # block 1
Change tabs into spaces (and wherever else in the file)

2022-10-07 13:03 UTC, eyip002 requested changes

2022-10-07 13:03 UTC, eyip002 commented on server/src/interlockers/simple_sectional.bahn
> +    # 1. Determine the segments where the two routes intersect.
Continue numbering the comments

2022-10-07 13:03 UTC, eyip002 commented on server/src/interlockers/simple_sectional.bahn
> +            seg_id_occurrences_counter = seg_id_occurrences_counter + 1
Use `+=` so that the SCCharts compiler does not complain about the use of "old style" relative updates.

2022-10-07 13:03 UTC, eyip002 commented on server/src/interlockers/simple_sectional.bahn
> +        current_path_index = current_path_index + 1
+=

2022-10-07 13:03 UTC, eyip002 commented on server/src/interlockers/simple_sectional.bahn
> +        current_path_index_2 = current_path_index_2 + 1
+=

2022-10-07 14:06 UTC, eyip002 requested changes

2022-10-07 14:06 UTC, eyip002 commented on server/src/interlockers/simple_sectional.bahn
> +    for string path_item in route_path0
Does this line compile for you?

2022-10-07 14:21 UTC, BLuedtke commented on server/src/interlockers/simple_sectional.bahn
> +    for string path_item in route_path0
No. Was a typo; next commit fixes it

2022-10-07 15:44 UTC, eyip002 approved these changes

2022-10-07 15:44 UTC, merged